"""
30s full-quality pipeline test (ALL on the A10G):
  F5 voice -> SadTalker HQ (gfpgan, 512) BIG presenter (~half screen)
  + blue_x shader bg + title slides + ace music -> NVENC mp4

Run in the audio_pipeline venv (has f5_tts + moderngl + PIL):
  /home/ubuntu/audio_pipeline/venv/bin/python /home/ubuntu/reel_build/compose_test30.py
"""
import os, sys, glob, subprocess
sys.path.insert(0, "/home/ubuntu/video-creator-backend")
from PIL import Image, ImageDraw, ImageFont
from services.f5tts_service import generate_speech
from services import shader_service
from services.shader_service import render_shader_video

W, H, FPS = 1080, 1920, 30
VOICE, SPEED, GAP = "female_confident", 0.85, 0.4
WORK = "/home/ubuntu/reel_build"
PRESENTER_SRC = "/home/ubuntu/SadTalker/st_face.jpg"
AMBIENT = "/home/ubuntu/reel_build/ace_music.wav"
OUT = "/home/ubuntu/test30.mp4"
SAD_DIR = "/home/ubuntu/SadTalker"
SAD_PY = "/home/ubuntu/SadTalker/venv_sadtalker/bin/python"
FB = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
FR = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
ACCENT, WHITE = (150, 210, 255), (245, 247, 252)

# BIG presenter (~half screen): 900px circle, lower-center
BG = 900
BG_X = (W - BG) // 2
BG_Y = H - BG - 70

shader_service.SHADER_TEMPLATES["blue_x"] = {"file": "blue_x.glsl", "name": "Blue X"}

SCENES = [
    dict(narr="Hey there — welcome to a quick quality test of the TrigunAI video pipeline. Everything you are seeing right now was generated by AI.",
         title="TrigunAI Pipeline", sub="Full-quality test"),
    dict(narr="The voice you are hearing, the moving background, the music, and this presenter talking to you — none of it was filmed.",
         title="100% AI generated", sub="Voice · background · music · presenter"),
    dict(narr="The lip sync runs at full quality on our own GPU. Take a close look at the detail.",
         title="SadTalker · GFPGAN", sub="Look at the detail"),
]


def dur(p):
    r = subprocess.run(["ffprobe", "-v", "quiet", "-show_entries", "format=duration",
                        "-of", "csv=p=0", p], capture_output=True, text=True)
    return float(r.stdout.strip()) if r.stdout.strip() else 0.0


def _f(p, s):
    return ImageFont.truetype(p, int(s))


def wrap(d, t, f, mw):
    w, lines, cur = t.split(), [], ""
    for x in w:
        s = (cur + " " + x).strip()
        if d.textlength(s, font=f) <= mw:
            cur = s
        else:
            lines.append(cur); cur = x
    if cur:
        lines.append(cur)
    return lines


def slide(sc, out):
    img = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    sd = ImageDraw.Draw(img)
    # top scrim for title legibility
    for y in range(H):
        a = int(150 * (1 - y / 520)) if y < 520 else 0
        if a > 0:
            sd.line([(0, y), (W, y)], fill=(4, 10, 22, a))
    d = ImageDraw.Draw(img)
    ft, fs = _f(FB, 96), _f(FR, 50)
    tl = wrap(d, sc["title"], ft, W - 160)
    y = 230
    # panel behind title
    asc, desc = ft.getmetrics()
    th = len(tl) * (asc + desc) + 70 + (asc + desc)
    d.rounded_rectangle([70, y - 40, W - 70, y + th], radius=40,
                        fill=(6, 12, 28, 180), outline=(*ACCENT, 110), width=2)
    for ln in tl:
        d.text((W // 2, y), ln, font=ft, fill=WHITE, anchor="ma"); y += asc + desc + 4
    y += 14
    d.text((W // 2, y), sc["sub"], font=fs, fill=ACCENT, anchor="ma")
    img.save(out)
    return out


def circle_mask(out, sz):
    m = Image.new("L", (sz, sz), 0)
    ImageDraw.Draw(m).ellipse([0, 0, sz - 1, sz - 1], fill=255); m.save(out); return out


def ring(out, sz, mg=10):
    r = Image.new("RGBA", (sz + 2 * mg, sz + 2 * mg), (0, 0, 0, 0))
    ImageDraw.Draw(r).ellipse([mg - 5, mg - 5, mg + sz + 4, mg + sz + 4], outline=(*ACCENT, 255), width=8)
    r.save(out); return out


# 1. voice
print(">> voice")
parts = []
for i, sc in enumerate(SCENES):
    w = os.path.join(WORK, f"t30_v{i}.wav")
    r = generate_speech(sc["narr"], tone=VOICE, speed=SPEED, output_path=w)
    sc["dur"] = r["duration"]; parts.append(w)
    print(f"   s{i}: {r['duration']:.2f}s")
# build full voice with gaps
sil = os.path.join(WORK, "t30_gap.wav")
subprocess.run(["ffmpeg", "-y", "-f", "lavfi", "-i", "anullsrc=r=24000:cl=mono", "-t", str(GAP), sil], capture_output=True)
clips = []
for i, p in enumerate(parts):
    clips.append(p)
    if i < len(parts) - 1:
        clips.append(sil)
ins, fc, lbl = [], [], []
for i, c in enumerate(clips):
    ins += ["-i", c]; fc.append(f"[{i}:a]aresample=24000,aformat=channel_layouts=mono[a{i}]"); lbl.append(f"[a{i}]")
fc.append("".join(lbl) + f"concat=n={len(clips)}:v=0:a=1[o]")
full = os.path.join(WORK, "t30_voice.wav")
subprocess.run(["ffmpeg", "-y"] + ins + ["-filter_complex", ";".join(fc), "-map", "[o]", full], check=True, capture_output=True)
TOTAL = dur(full)
t = 0.0
for i, sc in enumerate(SCENES):
    sc["start"] = t; sc["end"] = t + sc["dur"] + (GAP if i < len(SCENES) - 1 else 0)
    t = sc["end"]
SCENES[-1]["end"] = TOTAL
print(f"   TOTAL {TOTAL:.2f}s")

# 2. SadTalker HQ presenter (gfpgan 512)
print(">> SadTalker HQ (gfpgan 512)")
rd = os.path.join(WORK, "t30_sad")
subprocess.run(["rm", "-rf", rd]); os.makedirs(rd, exist_ok=True)
_env = {**os.environ, "PYTHONHASHSEED": "0"}
_env.pop("PYTHONNOUSERSITE", None)
r = subprocess.run([SAD_PY, "inference.py", "--source_image", PRESENTER_SRC,
                    "--driven_audio", full, "--result_dir", rd,
                    "--enhancer", "gfpgan", "--size", "512", "--preprocess", "crop", "--still"],
                   cwd=SAD_DIR, capture_output=True, text=True, env=_env)
mp4s = sorted(glob.glob(os.path.join(rd, "*.mp4")), key=os.path.getsize, reverse=True)
if not mp4s:
    print("SADTALKER FAIL:\n", r.stdout[-1500:], r.stderr[-1500:]); sys.exit(1)
presenter = mp4s[0]
print(f"   presenter = {presenter} ({dur(presenter):.2f}s)")

# 3. slides
print(">> slides")
slides = [slide(sc, os.path.join(WORK, f"t30_s{i}.png")) for i, sc in enumerate(SCENES)]

mask = circle_mask(os.path.join(WORK, "t30_mask.png"), BG)
rng = ring(os.path.join(WORK, "t30_ring.png"), BG, 10)

# 4. shader bg
print(">> blue_x shader bg")
shader_bg = os.path.join(WORK, "t30_bg.mp4")
render_shader_video(shader_name="blue_x", audio_path=full, output_path=shader_bg,
                    duration=TOTAL, fps=FPS, width=W, height=H)

# 5. composite (NVENC)
print(">> composite")
inputs = ["-i", shader_bg]
for s in slides:
    inputs += ["-loop", "1", "-t", f"{TOTAL:.2f}", "-i", s]
n = len(slides)
hi = 1 + n;  inputs += ["-i", presenter]
mi = hi + 1; inputs += ["-loop", "1", "-t", f"{TOTAL:.2f}", "-i", mask]
ri = mi + 1; inputs += ["-loop", "1", "-t", f"{TOTAL:.2f}", "-i", rng]
vi = ri + 1; inputs += ["-i", full]
ai = vi + 1; inputs += ["-i", AMBIENT]

fc, base = [], "0:v"
for i, sc in enumerate(SCENES):
    s, e = sc["start"], sc["end"]
    fc.append(f"[{i+1}:v]scale={W}:{H},format=rgba,fade=t=in:st={s:.2f}:d=0.3:alpha=1,"
              f"fade=t=out:st={max(s,e-0.3):.2f}:d=0.3:alpha=1[s{i}];"
              f"[{base}][s{i}]overlay=0:0:enable='between(t,{s:.2f},{e:.2f})'[v{i}]")
    base = f"v{i}"
fc.append(f"[{hi}:v]tpad=stop_mode=clone:stop_duration=3,scale={BG}:{BG},setsar=1,format=rgba[hb]")
fc.append(f"[{mi}:v]format=gray,scale={BG}:{BG}[mk]")
fc.append("[hb][mk]alphamerge[hc]")
fc.append(f"[{base}][hc]overlay={BG_X}:{BG_Y}[o1]")
fc.append(f"[o1][{ri}:v]overlay={BG_X-10}:{BG_Y-10}[o2]")
fc.append("[o2]format=yuv420p[v]")
fc.append(f"[{ai}:a]atrim=0:{TOTAL:.2f},volume=0.30,afade=t=in:st=0:d=2,afade=t=out:st={max(0,TOTAL-2):.2f}:d=2[mus]")
fc.append(f"[{vi}:a][mus]amix=inputs=2:duration=first:normalize=0[a]")

cmd = ["ffmpeg", "-y"] + inputs + ["-filter_complex", ";".join(fc),
       "-map", "[v]", "-map", "[a]", "-c:v", "h264_nvenc", "-preset", "p5", "-cq", "21",
       "-pix_fmt", "yuv420p", "-c:a", "aac", "-b:a", "192k", "-t", f"{TOTAL:.2f}", OUT]
r = subprocess.run(cmd, capture_output=True, text=True)
if r.returncode != 0:
    print("FFMPEG ERR:\n", r.stderr[-2500:]); sys.exit(1)
print(f"DONE -> {OUT} ({dur(OUT):.1f}s, {os.path.getsize(OUT)//1024//1024} MB)")
