"""
Compose the Module-1 reel: "Build a VR App - Without Writing Code"  (v4 full lip-sync)

  6 per-scene F5-TTS voice clips (0.45 + atempo 0.82) + 1.0s pauses  -> slow pace
+ blue_x shader background (1080x1920, voice-reactive two-tone X pattern)
+ 6 transparent vertical slides (staggered bullet build on scene 3)
+ FULL-VIDEO HALLO2 lip-synced talking head, circular (400px), persistent
+ ambient music bed (low)
= module01_reel.mp4   (9:16, vertical, ~59s)

Voice is regenerated by regen_voice.py (run that first). This script uses --skip-voice
to reuse voice_sX.wav + full_voice.wav (which already bakes in atempo + gaps).

Run:
  /home/ubuntu/audio_pipeline/venv/bin/python /home/ubuntu/reel_build/compose_reel.py --skip-voice
Flags: --skip-voice --skip-hallo --skip-shader
"""
import os, sys, subprocess
sys.path.insert(0, "/home/ubuntu/video-creator-backend")
from PIL import Image, ImageDraw, ImageFont
from services.f5tts_service import generate_speech
from services import shader_service
from services.shader_service import render_shader_video
from services.hallo2_service import generate_avatar

W, H, FPS = 1080, 1920, 30
SHADER = "blue_x"
VOICE = "female_confident"
SPEED = 0.45
GAP = 1.0                          # must match regen_voice.py
AMBIENT = "/home/ubuntu/welcome_voice/bg_ambient.mp3"
PRESENTER_SRC = "/home/ubuntu/reel_presenter.png"
WORK = "/home/ubuntu/reel_build"
OUT = "/home/ubuntu/module01_reel.mp4"
HALLO_FULL = os.path.join(WORK, "hallo_full.mp4")
os.makedirs(WORK, exist_ok=True)

shader_service.SHADER_TEMPLATES["blue_x"] = {
    "file": "blue_x.glsl", "name": "Blue X", "desc": "Two-tone blue X/bowtie",
    "mood": "brand", "colors": "blue/cyan", "category": "brand",
}

FONT_BOLD = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
FONT_REG = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
FONT_MONO = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
ACCENT = (150, 210, 255)
WHITE = (245, 247, 252)
GREY = (200, 210, 225)

# persistent lip-sync circle (big enough to read lips), bottom-center
PC = 400
PC_X = (W - PC) // 2
PC_Y = H - PC - 150

SCENES = [
    dict(id="s1", kind="center",
         narration="You can build a real VR app for your Quest headset. Without writing a single line of code.",
         title="Build a VR App", subtitle="Without writing code"),
    dict(id="s2", kind="prompt",
         narration="Never written C sharp? It doesn't matter. You describe what you want in plain English.",
         title="No coding experience?", body="Just describe what you want.",
         prompt="make this stone grabbable"),
    dict(id="s3", kind="bullets",
         narration="An AI coding agent, Claude Code, writes the script. You test it in VR. You iterate. That's how developers build in 2026.",
         title="AI writes the code",
         bullets=["You describe it", "Claude Code writes it", "You test in VR"]),
    dict(id="s4", kind="center",
         narration="I built a VR app called EnergyField. It's live in Meta's alpha program. I'll show you every step. Every bug. Every fix.",
         title="Built it myself", subtitle="EnergyField  -  live in Meta alpha",
         body="Every step. Every bug. Every fix."),
    dict(id="s5", kind="center",
         narration="By the end, you ship to the Meta Store. And on day one, you're standing inside your own VR room.",
         title="Day one", subtitle="Ship to the Meta Store",
         body="Standing in YOUR VR room"),
    dict(id="s6", kind="cta",
         narration="Start building. Link in the bio.",
         title="Start building", subtitle="Link in bio"),
]


def dur(path):
    r = subprocess.run(["ffprobe", "-v", "quiet", "-show_entries", "format=duration",
                        "-of", "csv=p=0", path], capture_output=True, text=True)
    return float(r.stdout.strip()) if r.stdout.strip() else 0.0


def _font(p, s):
    return ImageFont.truetype(p, int(s))


def wrap(draw, text, font, max_w):
    words, lines, cur = text.split(), [], ""
    for w in words:
        t = (cur + " " + w).strip()
        if draw.textlength(t, font=font) <= max_w:
            cur = t
        else:
            if cur:
                lines.append(cur)
            cur = w
    if cur:
        lines.append(cur)
    return lines


def render_reel_slide(scene, out_path, bullets_show=None):
    img = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    scrim = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    sd = ImageDraw.Draw(scrim)
    for y in range(H):
        if y < 360:
            a = int(150 * (1 - y / 360))
        elif y > 1380:
            a = int(180 * ((y - 1380) / (H - 1380)))
        else:
            a = 70
        sd.line([(0, y), (W, y)], fill=(4, 10, 22, a))
    img = Image.alpha_composite(img, scrim)
    draw = ImageDraw.Draw(img)

    pad_x = 90
    max_w = W - 2 * pad_x
    f_title = _font(FONT_BOLD, 92)
    f_sub = _font(FONT_REG, 50)
    f_body = _font(FONT_REG, 46)
    f_bul = _font(FONT_BOLD, 54)
    f_mono = _font(FONT_MONO, 44)

    blocks = []
    for ln in wrap(draw, scene["title"], f_title, max_w):
        blocks.append(("line", ln, f_title, WHITE, 6))
    blocks[-1] = blocks[-1][:4] + (34,)
    if scene.get("subtitle"):
        for ln in wrap(draw, scene["subtitle"], f_sub, max_w):
            blocks.append(("line", ln, f_sub, ACCENT, 8))
        blocks[-1] = blocks[-1][:4] + (28,)
    if scene["kind"] == "prompt":
        blocks.append(("prompt", scene["prompt"], f_mono, ACCENT, 24))
        if scene.get("body"):
            for ln in wrap(draw, scene["body"], f_body, max_w):
                blocks.append(("line", ln, f_body, GREY, 8))
    elif scene["kind"] == "bullets":
        n = bullets_show if bullets_show is not None else len(scene["bullets"])
        for i, b in enumerate(scene["bullets"]):
            col = WHITE if i < n else (110, 130, 150)
            blocks.append(("bullet", b, f_bul, col, 30))
    else:
        if scene.get("body"):
            for ln in wrap(draw, scene["body"], f_body, max_w):
                blocks.append(("line", ln, f_body, GREY, 8))

    def block_h(b):
        asc, desc = b[2].getmetrics()
        return asc + desc

    total_h = sum(block_h(b) + b[4] for b in blocks) - blocks[-1][4]
    cy = 660
    y = cy - total_h // 2

    panel_pad = 56
    panel = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    pd = ImageDraw.Draw(panel)
    pd.rounded_rectangle(
        [pad_x - panel_pad + 20, y - panel_pad, W - pad_x + panel_pad - 20, y + total_h + panel_pad],
        radius=44, fill=(6, 12, 28, 195), outline=(*ACCENT, 110), width=2)
    img = Image.alpha_composite(img, panel)
    draw = ImageDraw.Draw(img)

    for b in blocks:
        kind, content, font, color, gap = b
        if kind == "line":
            draw.text((W // 2, y), content, font=font, fill=color, anchor="ma")
        elif kind == "prompt":
            txt = "> " + content
            tw = draw.textlength(txt, font=font)
            bx0 = (W - tw) // 2 - 28
            bx1 = (W + tw) // 2 + 28
            asc, desc = font.getmetrics()
            draw.rounded_rectangle([bx0, y - 12, bx1, y + asc + desc + 12],
                                   radius=16, fill=(2, 8, 20, 220), outline=(*ACCENT, 170), width=2)
            draw.text((W // 2, y), txt, font=font, fill=ACCENT, anchor="ma")
        elif kind == "bullet":
            asc, desc = font.getmetrics()
            dot_r = 12
            tw = draw.textlength(content, font=font)
            row_w = dot_r * 2 + 28 + tw
            x0 = (W - row_w) // 2
            cyl = y + (asc + desc) // 2
            draw.ellipse([x0, cyl - dot_r, x0 + dot_r * 2, cyl + dot_r], fill=color)
            draw.text((x0 + dot_r * 2 + 28, y), content, font=font, fill=color, anchor="la")
        y += block_h(b) + gap

    if scene["kind"] == "cta":
        draw.line([(W // 2 - 90, y + 24), (W // 2 + 90, y + 24)], fill=(*ACCENT, 230), width=4)

    img.save(out_path, "PNG")
    return out_path


def build_circle_mask(out_path, size):
    m = Image.new("L", (size, size), 0)
    ImageDraw.Draw(m).ellipse([0, 0, size - 1, size - 1], fill=255)
    m.save(out_path)
    return out_path


def build_ring(out_path, size, margin=8):
    r = Image.new("RGBA", (size + 2 * margin, size + 2 * margin), (0, 0, 0, 0))
    ImageDraw.Draw(r).ellipse([margin - 4, margin - 4, margin + size + 3, margin + size + 3],
                              outline=(*ACCENT, 255), width=6)
    r.save(out_path)
    return out_path


# ================================================================ run
if "--skip-voice" not in sys.argv:
    print(">> 1. voiceover (run regen_voice.py instead for atempo+gaps)")
    for sc in SCENES:
        wav = os.path.join(WORK, f"voice_{sc['id']}.wav")
        r = generate_speech(sc["narration"], tone=VOICE, speed=SPEED, output_path=wav)
        sc["wav"], sc["dur"] = wav, r["duration"]
else:
    for sc in SCENES:
        sc["wav"] = os.path.join(WORK, f"voice_{sc['id']}.wav")
        sc["dur"] = dur(sc["wav"])

full_voice = os.path.join(WORK, "full_voice.wav")   # built by regen_voice.py (with gaps)
TOTAL = dur(full_voice)

# scene windows WITH gaps (matches regen_voice concat: scene, gap, scene, gap, ...)
t = 0.0
for i, sc in enumerate(SCENES):
    sc["start"] = t
    sc["end"] = t + sc["dur"] + (GAP if i < len(SCENES) - 1 else 0.0)  # slide holds through pause
    t += sc["dur"] + (GAP if i < len(SCENES) - 1 else 0.0)
SCENES[-1]["end"] = TOTAL
print(f"   total={TOTAL:.2f}s")

# ---- FULL-LENGTH HALLO lip-sync
if "--skip-hallo" not in sys.argv:
    print(">> 2. HALLO2 lip-sync (FULL video, ~%.0fs -> long render)..." % TOTAL)
    res = generate_avatar(PRESENTER_SRC, full_voice, HALLO_FULL)
    print(f"   hallo full = {res['path']} ({res['duration']:.2f}s)")
    if not os.path.exists(HALLO_FULL) or res["duration"] < 1:
        print("   !! Hallo produced no usable video; aborting.")
        sys.exit(2)

# ---- slides
print(">> 3. slides")
overlays = []
for sc in SCENES:
    if sc["kind"] == "bullets":
        seg = (sc["end"] - sc["start"]) / 3.0
        for k in range(3):
            p = os.path.join(WORK, f"slide_{sc['id']}_{k}.png")
            render_reel_slide(sc, p, bullets_show=k + 1)
            s = sc["start"] + k * seg
            e = sc["end"] if k == 2 else sc["start"] + (k + 1) * seg + 0.4
            overlays.append((p, s, e))
    else:
        p = os.path.join(WORK, f"slide_{sc['id']}.png")
        render_reel_slide(sc, p)
        overlays.append((p, sc["start"], sc["end"]))

mask_pc = build_circle_mask(os.path.join(WORK, "mask_pc.png"), PC)
ring_pc = build_ring(os.path.join(WORK, "ring_pc.png"), PC, 8)

# ---- shader bg
shader_bg = os.path.join(WORK, "shader_bg.mp4")
if "--skip-shader" not in sys.argv:
    print(">> 4. blue_x shader bg")
    render_shader_video(shader_name=SHADER, audio_path=full_voice, output_path=shader_bg,
                        duration=TOTAL, fps=FPS, width=W, height=H)

# ---- composite
print(">> 5. composite (full-video lip-sync presenter)")
inputs = ["-i", shader_bg]
for p, _, _ in overlays:
    inputs += ["-loop", "1", "-t", f"{TOTAL:.2f}", "-i", p]
n_ov = len(overlays)
h_idx = 1 + n_ov;     inputs += ["-i", HALLO_FULL]
mp_idx = h_idx + 1;   inputs += ["-loop", "1", "-t", f"{TOTAL:.2f}", "-i", mask_pc]
rp_idx = mp_idx + 1;  inputs += ["-loop", "1", "-t", f"{TOTAL:.2f}", "-i", ring_pc]
v_idx = rp_idx + 1;   inputs += ["-i", full_voice]
a_idx = v_idx + 1;    inputs += ["-i", AMBIENT]

fc, base = [], "0:v"
fade = 0.3
for i, (p, s, e) in enumerate(overlays):
    lbl = f"v{i}"
    fc.append(
        f"[{i+1}:v]scale={W}:{H},format=rgba,"
        f"fade=t=in:st={s:.2f}:d={fade}:alpha=1,fade=t=out:st={max(s, e-fade):.2f}:d={fade}:alpha=1[s{i}];"
        f"[{base}][s{i}]overlay=0:0:enable='between(t,{s:.2f},{e:.2f})'[{lbl}]"
    )
    base = lbl

# persistent circular lip-sync presenter
fc.append(f"[{h_idx}:v]tpad=stop_mode=clone:stop_duration=3,scale={PC}:{PC},setsar=1,format=rgba[hb]")
fc.append(f"[{mp_idx}:v]format=gray,scale={PC}:{PC}[mkp]")
fc.append("[hb][mkp]alphamerge[hc]")
fc.append(f"[{base}][hc]overlay={PC_X}:{PC_Y}[o1]")
fc.append(f"[o1][{rp_idx}:v]overlay={PC_X-8}:{PC_Y-8}[o2]")
fc.append("[o2]format=yuv420p[v]")

fc.append(f"[{a_idx}:a]atrim=0:{TOTAL:.2f},volume=0.08,afade=t=in:st=0:d=2,"
          f"afade=t=out:st={max(0,TOTAL-2):.2f}:d=2[mus]")
fc.append(f"[{v_idx}:a][mus]amix=inputs=2:duration=first:normalize=0[a]")

cmd = ["ffmpeg", "-y"] + inputs + [
    "-filter_complex", ";".join(fc),
    "-map", "[v]", "-map", "[a]",
    "-c:v", "h264_nvenc", "-preset", "p5", "-cq", "23", "-pix_fmt", "yuv420p",
    "-c:a", "aac", "-b:a", "192k", "-t", f"{TOTAL:.2f}", OUT,
]
r = subprocess.run(cmd, capture_output=True, text=True)
if r.returncode != 0:
    print("FFMPEG ERROR:\n", r.stderr[-2800:])
    sys.exit(1)
print(f"DONE -> {OUT}  ({dur(OUT):.1f}s, {os.path.getsize(OUT)//1024//1024} MB)")
