"""NEET Biology taxonomy — NCERT Class 11 + 12 chapter names.

Same shape as the JEE taxonomies (see syllabus.py): chapter -> {keywords, concepts}.
Chapter names follow the NCERT textbook chapter titles, because that is the vocabulary
NEET students (and coaching material) actually use — "Molecular Basis of Inheritance",
not "Genetics II".

Coverage note: a few chapters rationalised out of the 2024 NEET syllabus (Transport in
Plants, Mineral Nutrition, Digestion and Absorption, Reproduction in Organisms,
Strategies for Enhancement in Food Production, Environmental Issues) are KEPT here.
Older past-paper and open-dataset questions still test them, and a missing chapter
forces the tagger to mis-file those questions somewhere wrong.
"""

NEET_BIOLOGY = {
    # --- Unit 1: Diversity in the Living World ------------------------------
    "The Living World": {
        "keywords": ["taxonomy", "nomenclature", "binomial", "taxon", "herbarium",
                     "botanical garden", "museum", "zoological park", "key", "flora",
                     "manual", "monograph", "systematics", "species concept"],
        "concepts": {
            "Taxonomic Categories & Hierarchy": ["taxon", "hierarchy", "genus", "family", "order"],
            "Nomenclature": ["binomial", "nomenclature", "icbn", "icZn"],
            "Taxonomical Aids": ["herbarium", "botanical garden", "museum", "zoological park", "flora", "monograph"],
        },
    },
    "Biological Classification": {
        "keywords": ["monera", "protista", "fungi", "whittaker", "five kingdom",
                     "archaebacteria", "eubacteria", "cyanobacteria", "mycoplasma",
                     "dinoflagellate", "euglenoid", "slime mould", "ascomycetes",
                     "basidiomycetes", "deuteromycetes", "phycomycetes", "lichen",
                     "mycorrhiza", "virus", "viroid", "prion", "bacteriophage"],
        "concepts": {
            "Five Kingdom Classification": ["whittaker", "five kingdom", "kingdom"],
            "Kingdom Monera": ["archaebacteria", "eubacteria", "cyanobacteria", "mycoplasma", "bacteria"],
            "Kingdom Protista": ["dinoflagellate", "euglenoid", "slime mould", "protozoa", "diatom"],
            "Kingdom Fungi": ["ascomycetes", "basidiomycetes", "deuteromycetes", "phycomycetes", "fungi"],
            "Viruses, Viroids & Lichens": ["virus", "viroid", "prion", "lichen", "bacteriophage"],
        },
    },
    "Plant Kingdom": {
        "keywords": ["algae", "bryophyta", "pteridophyta", "gymnosperm", "angiosperm",
                     "chlorophyceae", "phaeophyceae", "rhodophyceae", "moss", "liverwort",
                     "fern", "prothallus", "heterospory", "alternation of generations",
                     "protonema", "archegonium", "antheridium"],
        "concepts": {
            "Algae": ["algae", "chlorophyceae", "phaeophyceae", "rhodophyceae"],
            "Bryophytes": ["bryophyta", "moss", "liverwort", "protonema"],
            "Pteridophytes": ["pteridophyta", "fern", "prothallus", "heterospory"],
            "Gymnosperms & Angiosperms": ["gymnosperm", "angiosperm", "cycas", "pinus"],
            "Life Cycle Patterns": ["alternation of generations", "haplontic", "diplontic"],
        },
    },
    "Animal Kingdom": {
        "keywords": ["porifera", "coelenterata", "cnidaria", "ctenophora", "platyhelminthes",
                     "aschelminthes", "annelida", "arthropoda", "mollusca", "echinodermata",
                     "hemichordata", "chordata", "notochord", "coelom", "triploblastic",
                     "diploblastic", "metamerism", "amphibia", "reptilia", "aves", "mammalia",
                     "pisces", "cyclostomata", "osteichthyes", "chondrichthyes"],
        "concepts": {
            "Basis of Classification": ["coelom", "symmetry", "triploblastic", "diploblastic", "notochord", "metamerism"],
            "Non-Chordate Phyla": ["porifera", "coelenterata", "platyhelminthes", "annelida",
                                   "arthropoda", "mollusca", "echinodermata"],
            "Chordates & Vertebrate Classes": ["chordata", "amphibia", "reptilia", "aves", "mammalia",
                                               "cyclostomata", "osteichthyes", "chondrichthyes"],
        },
    },

    # --- Unit 2: Structural Organisation ------------------------------------
    "Morphology of Flowering Plants": {
        "keywords": ["inflorescence", "aestivation", "placentation", "phyllotaxy",
                     "venation", "root system", "taproot", "fibrous root", "modification of stem",
                     "floral formula", "racemose", "cymose", "corolla", "calyx", "androecium",
                     "gynoecium", "fruit", "seed coat", "leaf", "stipule"],
        "concepts": {
            "Root, Stem & Leaf": ["taproot", "fibrous root", "modification of stem", "phyllotaxy", "venation", "stipule"],
            "Inflorescence & Flower": ["inflorescence", "racemose", "cymose", "calyx", "corolla",
                                       "androecium", "gynoecium", "aestivation"],
            "Placentation": ["placentation", "parietal", "axile", "basal"],
            "Fruit & Seed": ["fruit", "seed coat", "pericarp"],
        },
    },
    "Anatomy of Flowering Plants": {
        "keywords": ["meristem", "parenchyma", "collenchyma", "sclerenchyma", "xylem",
                     "phloem", "vascular bundle", "epidermis", "stomata", "cambium",
                     "secondary growth", "annual ring", "periderm", "casparian strip",
                     "endodermis", "pericycle", "dicot stem", "monocot stem", "bulliform"],
        "concepts": {
            "Meristematic & Permanent Tissues": ["meristem", "parenchyma", "collenchyma", "sclerenchyma"],
            "Tissue Systems": ["epidermis", "stomata", "endodermis", "pericycle", "casparian strip"],
            "Anatomy of Dicot & Monocot": ["dicot stem", "monocot stem", "vascular bundle", "bulliform"],
            "Secondary Growth": ["secondary growth", "cambium", "annual ring", "periderm"],
        },
    },
    "Structural Organisation in Animals": {
        "keywords": ["epithelial tissue", "connective tissue", "muscular tissue", "neural tissue",
                     "frog", "cockroach", "earthworm", "squamous", "cuboidal", "columnar",
                     "tight junction", "gap junction", "adhering junction", "areolar",
                     "nephridia", "clitellum", "setae", "hepatic caeca"],
        "concepts": {
            "Animal Tissues": ["epithelial tissue", "connective tissue", "muscular tissue",
                               "neural tissue", "squamous", "cuboidal", "columnar", "areolar"],
            "Cell Junctions": ["tight junction", "gap junction", "adhering junction"],
            "Earthworm, Cockroach & Frog": ["earthworm", "cockroach", "frog", "nephridia",
                                            "clitellum", "setae", "hepatic caeca"],
        },
    },

    # --- Unit 3: Cell Structure and Function --------------------------------
    "Cell: The Unit of Life": {
        "keywords": ["plasma membrane", "cell wall", "mitochondria", "chloroplast",
                     "endoplasmic reticulum", "golgi", "lysosome", "vacuole", "ribosome",
                     "nucleus", "chromatin", "nucleolus", "centriole", "cilia", "flagella",
                     "prokaryotic", "eukaryotic", "mesosome", "fluid mosaic", "cytoskeleton",
                     "microbodies", "plastid"],
        "concepts": {
            "Prokaryotic Cell": ["prokaryotic", "mesosome", "nucleoid", "pili"],
            "Cell Membrane & Wall": ["plasma membrane", "fluid mosaic", "cell wall"],
            "Cell Organelles": ["mitochondria", "chloroplast", "endoplasmic reticulum", "golgi",
                                "lysosome", "vacuole", "ribosome", "plastid", "microbodies"],
            "Nucleus & Chromosomes": ["nucleus", "chromatin", "nucleolus", "chromosome"],
            "Cytoskeleton, Cilia & Flagella": ["cytoskeleton", "cilia", "flagella", "centriole"],
        },
    },
    "Biomolecules": {
        "keywords": ["amino acid", "protein", "carbohydrate", "lipid", "nucleic acid",
                     "enzyme", "polysaccharide", "peptide bond", "primary structure",
                     "cofactor", "coenzyme", "competitive inhibitor", "allosteric",
                     "michaelis", "metabolite", "glycosidic", "zwitterion"],
        "concepts": {
            "Amino Acids & Proteins": ["amino acid", "protein", "peptide bond", "zwitterion",
                                       "primary structure", "quaternary"],
            "Carbohydrates & Lipids": ["carbohydrate", "polysaccharide", "lipid", "glycosidic"],
            "Nucleic Acids": ["nucleic acid", "nucleotide", "nucleoside"],
            "Enzymes": ["enzyme", "cofactor", "coenzyme", "competitive inhibitor",
                        "allosteric", "michaelis", "activation energy"],
        },
    },
    "Cell Cycle and Cell Division": {
        "keywords": ["mitosis", "meiosis", "prophase", "metaphase", "anaphase", "telophase",
                     "interphase", "cytokinesis", "synapsis", "crossing over", "bivalent",
                     "chiasmata", "spindle", "g1 phase", "s phase", "g2 phase", "cell cycle",
                     "leptotene", "zygotene", "pachytene", "diplotene", "diakinesis"],
        "concepts": {
            "Cell Cycle Phases": ["cell cycle", "interphase", "g1 phase", "s phase", "g2 phase"],
            "Mitosis": ["mitosis", "prophase", "metaphase", "anaphase", "telophase", "cytokinesis"],
            "Meiosis": ["meiosis", "synapsis", "crossing over", "bivalent", "chiasmata",
                        "leptotene", "zygotene", "pachytene", "diplotene", "diakinesis"],
        },
    },

    # --- Unit 4: Plant Physiology -------------------------------------------
    "Transport in Plants": {
        "keywords": ["osmosis", "water potential", "plasmolysis", "imbibition", "transpiration",
                     "root pressure", "guttation", "cohesion", "apoplast", "symplast",
                     "mass flow hypothesis", "phloem loading", "diffusion pressure deficit"],
        "concepts": {
            "Water Potential & Osmosis": ["osmosis", "water potential", "plasmolysis", "imbibition"],
            "Transpiration & Ascent of Sap": ["transpiration", "root pressure", "guttation", "cohesion"],
            "Translocation": ["mass flow hypothesis", "phloem loading", "apoplast", "symplast"],
        },
    },
    "Mineral Nutrition": {
        "keywords": ["macronutrient", "micronutrient", "deficiency symptom", "hydroponics",
                     "nitrogen fixation", "nitrogenase", "leghaemoglobin", "nitrification",
                     "denitrification", "essential element", "chlorosis", "necrosis"],
        "concepts": {
            "Essential Elements & Deficiency": ["macronutrient", "micronutrient", "essential element",
                                                "deficiency symptom", "chlorosis", "necrosis"],
            "Nitrogen Metabolism": ["nitrogen fixation", "nitrogenase", "leghaemoglobin",
                                    "nitrification", "denitrification"],
        },
    },
    "Photosynthesis in Higher Plants": {
        "keywords": ["photosynthesis", "chlorophyll", "photosystem", "calvin cycle", "rubisco",
                     "c4 pathway", "hatch and slack", "photorespiration", "grana", "stroma",
                     "light reaction", "photophosphorylation", "kranz anatomy", "pep carboxylase",
                     "quantum yield", "red drop", "emerson"],
        "concepts": {
            "Light Reaction & Photosystems": ["photosystem", "light reaction", "photophosphorylation",
                                              "chlorophyll", "emerson", "red drop"],
            "Calvin Cycle (C3)": ["calvin cycle", "rubisco", "c3 pathway"],
            "C4 Pathway & Kranz Anatomy": ["c4 pathway", "hatch and slack", "kranz anatomy", "pep carboxylase"],
            "Photorespiration": ["photorespiration"],
        },
    },
    "Respiration in Plants": {
        "keywords": ["glycolysis", "krebs cycle", "tca cycle", "electron transport chain",
                     "oxidative phosphorylation", "fermentation", "respiratory quotient",
                     "atp synthase", "pyruvate", "acetyl coa", "anaerobic respiration",
                     "amphibolic"],
        "concepts": {
            "Glycolysis & Fermentation": ["glycolysis", "fermentation", "pyruvate", "anaerobic respiration"],
            "Krebs Cycle": ["krebs cycle", "tca cycle", "acetyl coa"],
            "ETS & Oxidative Phosphorylation": ["electron transport chain", "oxidative phosphorylation", "atp synthase"],
            "Respiratory Quotient": ["respiratory quotient", "amphibolic"],
        },
    },
    "Plant Growth and Development": {
        "keywords": ["auxin", "gibberellin", "cytokinin", "abscisic acid", "ethylene",
                     "photoperiodism", "vernalisation", "vernalization", "apical dominance",
                     "differentiation", "dedifferentiation", "senescence", "phytochrome",
                     "geometric growth", "plasticity", "heterophylly"],
        "concepts": {
            "Growth Phases & Differentiation": ["geometric growth", "differentiation",
                                                "dedifferentiation", "plasticity", "heterophylly"],
            "Plant Growth Regulators": ["auxin", "gibberellin", "cytokinin", "abscisic acid",
                                        "ethylene", "apical dominance"],
            "Photoperiodism & Vernalisation": ["photoperiodism", "vernalisation", "vernalization", "phytochrome"],
        },
    },

    # --- Unit 5: Human Physiology -------------------------------------------
    "Digestion and Absorption": {
        "keywords": ["digestion", "peristalsis", "villi", "bile", "pancreatic juice",
                     "trypsin", "pepsin", "amylase", "lipase", "gastric juice", "chyme",
                     "kwashiorkor", "marasmus", "dental formula", "liver", "gall bladder"],
        "concepts": {
            "Alimentary Canal & Glands": ["alimentary", "liver", "gall bladder", "dental formula", "peristalsis"],
            "Digestive Enzymes": ["trypsin", "pepsin", "amylase", "lipase", "bile", "gastric juice", "pancreatic juice"],
            "Absorption & Disorders": ["villi", "absorption", "kwashiorkor", "marasmus", "chyme"],
        },
    },
    "Breathing and Exchange of Gases": {
        "keywords": ["breathing", "alveoli", "tidal volume", "vital capacity", "residual volume",
                     "oxyhaemoglobin", "oxygen dissociation curve", "bohr effect", "carbaminohaemoglobin",
                     "chloride shift", "spirometer", "emphysema", "asthma", "diaphragm",
                     "inspiratory reserve", "expiratory reserve"],
        "concepts": {
            "Respiratory Volumes & Capacities": ["tidal volume", "vital capacity", "residual volume",
                                                 "inspiratory reserve", "expiratory reserve", "spirometer"],
            "Mechanism of Breathing": ["breathing", "diaphragm", "intercostal"],
            "Transport of Gases": ["oxyhaemoglobin", "oxygen dissociation curve", "bohr effect",
                                   "carbaminohaemoglobin", "chloride shift"],
            "Respiratory Disorders": ["emphysema", "asthma", "occupational"],
        },
    },
    "Body Fluids and Circulation": {
        "keywords": ["blood group", "rh factor", "coagulation", "plasma", "erythrocyte",
                     "leucocyte", "platelet", "lymph", "cardiac cycle", "ecg", "sa node",
                     "av node", "purkinje", "systole", "diastole", "double circulation",
                     "hypertension", "angina", "heart sound"],
        "concepts": {
            "Blood Composition & Groups": ["blood group", "rh factor", "plasma", "erythrocyte",
                                           "leucocyte", "platelet", "coagulation"],
            "Cardiac Cycle & ECG": ["cardiac cycle", "ecg", "systole", "diastole", "heart sound"],
            "Conducting System of Heart": ["sa node", "av node", "purkinje", "bundle of his"],
            "Circulatory Disorders": ["hypertension", "angina", "heart failure"],
        },
    },
    "Excretory Products and their Elimination": {
        "keywords": ["nephron", "glomerulus", "bowman", "ultrafiltration", "counter current",
                     "henle", "adh", "vasopressin", "juxtaglomerular", "renin", "angiotensin",
                     "uraemia", "dialysis", "ureotelic", "uricotelic", "ammonotelic",
                     "micturition", "kidney"],
        "concepts": {
            "Nephron & Urine Formation": ["nephron", "glomerulus", "bowman", "ultrafiltration",
                                          "henle", "reabsorption", "kidney"],
            "Regulation of Kidney Function": ["adh", "vasopressin", "juxtaglomerular", "renin",
                                              "angiotensin", "counter current"],
            "Modes of Excretion & Disorders": ["ureotelic", "uricotelic", "ammonotelic",
                                               "uraemia", "dialysis", "micturition"],
        },
    },
    "Locomotion and Movement": {
        "keywords": ["sarcomere", "actin", "myosin", "sliding filament", "tropomyosin",
                     "troponin", "myofibril", "sarcoplasmic reticulum", "joint", "ligament",
                     "tendon", "arthritis", "osteoporosis", "myasthenia gravis", "axial skeleton",
                     "appendicular", "vertebral column"],
        "concepts": {
            "Muscle Structure & Contraction": ["sarcomere", "actin", "myosin", "sliding filament",
                                               "tropomyosin", "troponin", "myofibril", "sarcoplasmic reticulum"],
            "Skeletal System & Joints": ["axial skeleton", "appendicular", "vertebral column",
                                         "joint", "ligament", "tendon"],
            "Disorders of Muscular & Skeletal System": ["arthritis", "osteoporosis", "myasthenia gravis", "gout"],
        },
    },
    "Neural Control and Coordination": {
        "keywords": ["neuron", "synapse", "action potential", "resting potential", "myelin",
                     "neurotransmitter", "reflex arc", "cerebrum", "cerebellum", "medulla",
                     "hypothalamus", "cranial nerve", "sympathetic", "parasympathetic",
                     "node of ranvier", "saltatory", "depolarisation", "eye", "ear",
                     "cochlea", "retina", "rods and cones"],
        "concepts": {
            "Neuron & Nerve Impulse": ["neuron", "action potential", "resting potential", "myelin",
                                       "node of ranvier", "saltatory", "depolarisation"],
            "Synaptic Transmission": ["synapse", "neurotransmitter", "acetylcholine"],
            "Central & Peripheral Nervous System": ["cerebrum", "cerebellum", "medulla", "hypothalamus",
                                                    "cranial nerve", "sympathetic", "parasympathetic", "reflex arc"],
            "Sense Organs (Eye & Ear)": ["eye", "ear", "cochlea", "retina", "rods and cones", "organ of corti"],
        },
    },
    "Chemical Coordination and Integration": {
        "keywords": ["hormone", "pituitary", "thyroid", "parathyroid", "adrenal", "pancreas",
                     "insulin", "glucagon", "thyroxine", "cortisol", "adrenaline", "oxytocin",
                     "melatonin", "pineal", "thymus", "goitre", "cretinism", "acromegaly",
                     "diabetes", "addison", "hypothalamus releasing"],
        "concepts": {
            "Endocrine Glands": ["pituitary", "thyroid", "parathyroid", "adrenal", "pancreas",
                                 "pineal", "thymus"],
            "Hormones & their Actions": ["hormone", "insulin", "glucagon", "thyroxine", "cortisol",
                                         "adrenaline", "oxytocin", "melatonin"],
            "Hormonal Disorders": ["goitre", "cretinism", "acromegaly", "diabetes", "addison", "dwarfism"],
        },
    },

    # --- Unit 6: Reproduction ------------------------------------------------
    "Reproduction in Organisms": {
        "keywords": ["asexual reproduction", "binary fission", "budding", "fragmentation",
                     "vegetative propagation", "gametogenesis", "juvenile phase", "oestrus",
                     "menstrual", "parthenogenesis", "oviparous", "viviparous", "zygote"],
        "concepts": {
            "Asexual Reproduction": ["asexual reproduction", "binary fission", "budding",
                                     "fragmentation", "vegetative propagation"],
            "Sexual Reproduction Phases": ["juvenile phase", "gametogenesis", "zygote",
                                           "oestrus", "parthenogenesis", "oviparous", "viviparous"],
        },
    },
    "Sexual Reproduction in Flowering Plants": {
        "keywords": ["microsporogenesis", "megasporogenesis", "embryo sac", "double fertilisation",
                     "double fertilization", "pollen", "pollination", "tapetum", "endosperm",
                     "apomixis", "polyembryony", "self incompatibility", "triple fusion",
                     "synergid", "antipodal", "integument", "ovule", "pollen tube"],
        "concepts": {
            "Microsporogenesis & Pollen": ["microsporogenesis", "pollen", "tapetum", "anther", "pollen tube"],
            "Megasporogenesis & Embryo Sac": ["megasporogenesis", "embryo sac", "synergid",
                                              "antipodal", "ovule", "integument"],
            "Pollination": ["pollination", "self incompatibility", "anemophily", "entomophily"],
            "Double Fertilisation & Endosperm": ["double fertilisation", "double fertilization",
                                                 "triple fusion", "endosperm"],
            "Apomixis & Polyembryony": ["apomixis", "polyembryony"],
        },
    },
    "Human Reproduction": {
        "keywords": ["spermatogenesis", "oogenesis", "menstrual cycle", "ovulation",
                     "corpus luteum", "graafian follicle", "implantation", "placenta",
                     "lactation", "seminiferous", "leydig", "sertoli", "acrosome", "capacitation",
                     "blastocyst", "parturition", "hcg", "colostrum", "gestation"],
        "concepts": {
            "Male Reproductive System & Spermatogenesis": ["spermatogenesis", "seminiferous",
                                                           "leydig", "sertoli", "acrosome"],
            "Female Reproductive System & Oogenesis": ["oogenesis", "graafian follicle", "corpus luteum"],
            "Menstrual Cycle": ["menstrual cycle", "ovulation", "luteal", "follicular"],
            "Fertilisation, Implantation & Pregnancy": ["capacitation", "implantation", "blastocyst",
                                                        "placenta", "hcg", "gestation"],
            "Parturition & Lactation": ["parturition", "lactation", "colostrum", "oxytocin"],
        },
    },
    "Reproductive Health": {
        "keywords": ["contraceptive", "iud", "tubectomy", "vasectomy", "mtp", "amniocentesis",
                     "art", "ivf", "zift", "gift", "icsi", "infertility", "std", "sexually transmitted",
                     "population explosion", "family planning", "saheli", "lactational amenorrhea"],
        "concepts": {
            "Contraception": ["contraceptive", "iud", "tubectomy", "vasectomy", "saheli",
                              "lactational amenorrhea", "family planning"],
            "MTP & Amniocentesis": ["mtp", "amniocentesis", "sex determination"],
            "Assisted Reproductive Technologies": ["art", "ivf", "zift", "gift", "icsi", "infertility"],
            "STDs & Population": ["std", "sexually transmitted", "population explosion"],
        },
    },

    # --- Unit 7: Genetics and Evolution --------------------------------------
    "Principles of Inheritance and Variation": {
        "keywords": ["mendel", "monohybrid", "dihybrid", "test cross", "incomplete dominance",
                     "codominance", "multiple allele", "epistasis", "linkage", "recombination",
                     "pedigree", "sex linked", "haemophilia", "colour blindness", "thalassemia",
                     "sickle cell", "down syndrome", "turner", "klinefelter", "punnett",
                     "law of segregation", "independent assortment", "polygenic"],
        "concepts": {
            "Mendelian Inheritance": ["mendel", "monohybrid", "dihybrid", "test cross", "punnett",
                                      "law of segregation", "independent assortment"],
            "Deviations from Mendelism": ["incomplete dominance", "codominance", "multiple allele",
                                          "epistasis", "polygenic"],
            "Linkage & Recombination": ["linkage", "recombination", "crossing over frequency"],
            "Sex Determination & Sex-Linked Inheritance": ["sex linked", "haemophilia",
                                                           "colour blindness", "sex determination"],
            "Genetic Disorders": ["down syndrome", "turner", "klinefelter", "thalassemia",
                                  "sickle cell", "phenylketonuria", "pedigree"],
        },
    },
    "Molecular Basis of Inheritance": {
        "keywords": ["dna", "rna", "replication", "transcription", "translation", "lac operon",
                     "genetic code", "griffith", "hershey", "chase", "avery", "meselson",
                     "okazaki", "primase", "helicase", "polymerase", "trna", "mrna", "codon",
                     "anticodon", "splicing", "intron", "exon", "human genome project",
                     "dna fingerprinting", "vntr", "nucleosome", "histone", "chargaff"],
        "concepts": {
            "DNA Structure & Packaging": ["dna", "nucleosome", "histone", "chargaff", "double helix"],
            "Search for Genetic Material": ["griffith", "hershey", "chase", "avery", "transforming principle"],
            "DNA Replication": ["replication", "meselson", "okazaki", "helicase", "primase", "semiconservative"],
            "Transcription & RNA Processing": ["transcription", "splicing", "intron", "exon", "capping", "tailing"],
            "Genetic Code & Translation": ["genetic code", "translation", "codon", "anticodon", "trna", "ribosome"],
            "Gene Regulation (lac operon)": ["lac operon", "operon", "repressor", "inducer"],
            "Human Genome Project & DNA Fingerprinting": ["human genome project", "dna fingerprinting", "vntr"],
        },
    },
    "Evolution": {
        "keywords": ["darwin", "natural selection", "lamarck", "hardy weinberg", "genetic drift",
                     "founder effect", "adaptive radiation", "homologous", "analogous",
                     "convergent evolution", "divergent evolution", "fossil", "miller urey",
                     "oparin", "haldane", "industrial melanism", "speciation", "australopithecus",
                     "homo erectus", "neanderthal", "gene pool", "allele frequency"],
        "concepts": {
            "Origin of Life": ["oparin", "haldane", "miller urey", "abiogenesis", "panspermia"],
            "Evidences of Evolution": ["homologous", "analogous", "fossil", "vestigial",
                                       "convergent evolution", "divergent evolution", "adaptive radiation"],
            "Theories: Darwin & Lamarck": ["darwin", "lamarck", "natural selection", "industrial melanism"],
            "Hardy-Weinberg & Genetic Drift": ["hardy weinberg", "genetic drift", "founder effect",
                                               "gene pool", "allele frequency", "bottleneck"],
            "Human Evolution": ["australopithecus", "homo erectus", "neanderthal", "homo habilis", "ramapithecus"],
        },
    },

    # --- Unit 8: Biology in Human Welfare ------------------------------------
    "Human Health and Disease": {
        "keywords": ["malaria", "typhoid", "pneumonia", "amoebiasis", "ascariasis", "filariasis",
                     "ringworm", "immunity", "antibody", "antigen", "vaccine", "allergy",
                     "autoimmune", "aids", "hiv", "cancer", "oncogene", "metastasis",
                     "drug abuse", "cannabinoid", "opioid", "morphine", "interferon",
                     "innate immunity", "acquired immunity", "plasmodium", "widal"],
        "concepts": {
            "Common Diseases in Humans": ["malaria", "typhoid", "pneumonia", "amoebiasis",
                                          "ascariasis", "filariasis", "ringworm", "plasmodium", "widal"],
            "Immunity & Immune System": ["immunity", "antibody", "antigen", "vaccine",
                                         "innate immunity", "acquired immunity", "interferon"],
            "Allergy & Autoimmunity": ["allergy", "histamine", "autoimmune"],
            "AIDS & Cancer": ["aids", "hiv", "cancer", "oncogene", "metastasis", "carcinogen"],
            "Drugs & Alcohol Abuse": ["drug abuse", "cannabinoid", "opioid", "morphine", "cocaine"],
        },
    },
    "Microbes in Human Welfare": {
        "keywords": ["lactobacillus", "saccharomyces", "penicillin", "cyclosporin", "statin",
                     "biogas", "methanogen", "sewage treatment", "activated sludge", "bod",
                     "biofertiliser", "biofertilizer", "rhizobium", "mycorrhiza", "biocontrol",
                     "bacillus thuringiensis", "trichoderma", "baculovirus", "streptokinase",
                     "curdling", "fermentor"],
        "concepts": {
            "Microbes in Household & Industrial Products": ["lactobacillus", "saccharomyces",
                                                            "curdling", "fermentor", "penicillin",
                                                            "cyclosporin", "statin", "streptokinase"],
            "Sewage Treatment & Biogas": ["sewage treatment", "activated sludge", "bod",
                                          "biogas", "methanogen"],
            "Biofertilisers & Biocontrol": ["biofertiliser", "biofertilizer", "rhizobium",
                                            "mycorrhiza", "biocontrol", "bacillus thuringiensis",
                                            "trichoderma", "baculovirus"],
        },
    },
    "Strategies for Enhancement in Food Production": {
        "keywords": ["plant breeding", "hybridisation", "mutation breeding", "biofortification",
                     "tissue culture", "micropropagation", "somatic hybridisation", "apiculture",
                     "aquaculture", "pisciculture", "poultry", "inbreeding", "outbreeding",
                     "mule", "single cell protein", "green revolution", "explant", "callus"],
        "concepts": {
            "Animal Husbandry": ["apiculture", "aquaculture", "pisciculture", "poultry",
                                 "inbreeding", "outbreeding", "mule"],
            "Plant Breeding": ["plant breeding", "hybridisation", "mutation breeding",
                               "biofortification", "green revolution"],
            "Tissue Culture & SCP": ["tissue culture", "micropropagation", "somatic hybridisation",
                                     "explant", "callus", "single cell protein"],
        },
    },

    # --- Unit 9: Biotechnology -----------------------------------------------
    "Biotechnology: Principles and Processes": {
        "keywords": ["restriction enzyme", "ecori", "plasmid", "vector", "cloning", "pbr322",
                     "ligase", "pcr", "taq polymerase", "gel electrophoresis", "bioreactor",
                     "competent cell", "selectable marker", "insertional inactivation",
                     "agrobacterium", "recombinant dna", "palindromic", "downstream processing"],
        "concepts": {
            "Tools of Recombinant DNA Technology": ["restriction enzyme", "ecori", "ligase",
                                                    "plasmid", "vector", "pbr322", "palindromic",
                                                    "agrobacterium"],
            "Cloning & Transformation": ["cloning", "competent cell", "selectable marker",
                                         "insertional inactivation", "recombinant dna"],
            "PCR & Electrophoresis": ["pcr", "taq polymerase", "gel electrophoresis"],
            "Bioreactors & Downstream Processing": ["bioreactor", "downstream processing"],
        },
    },
    "Biotechnology and its Applications": {
        "keywords": ["bt cotton", "bt toxin", "cry protein", "rnai", "golden rice", "gmo",
                     "transgenic", "gene therapy", "adenosine deaminase", "insulin humulin",
                     "molecular diagnosis", "elisa", "biopiracy", "biopatent", "nematode",
                     "meloidogyne", "rosie"],
        "concepts": {
            "Transgenic Plants & Bt Crops": ["bt cotton", "bt toxin", "cry protein", "golden rice",
                                             "transgenic", "gmo", "rnai", "meloidogyne"],
            "Transgenic Animals & Gene Therapy": ["transgenic animal", "gene therapy",
                                                  "adenosine deaminase", "rosie"],
            "Biotechnology in Medicine": ["insulin humulin", "molecular diagnosis", "elisa"],
            "Ethical Issues & Biopiracy": ["biopiracy", "biopatent", "gmo release"],
        },
    },

    # --- Unit 10: Ecology and Environment ------------------------------------
    "Organisms and Populations": {
        "keywords": ["population", "age pyramid", "exponential growth", "logistic growth",
                     "carrying capacity", "mutualism", "commensalism", "parasitism",
                     "predation", "competition", "gause", "niche", "hibernation", "aestivation",
                     "migration", "population density", "natality", "mortality", "biome"],
        "concepts": {
            "Population Attributes & Growth": ["population density", "natality", "mortality",
                                               "age pyramid", "exponential growth", "logistic growth",
                                               "carrying capacity"],
            "Population Interactions": ["mutualism", "commensalism", "parasitism", "predation",
                                        "competition", "gause", "niche"],
            "Adaptations & Responses": ["hibernation", "aestivation", "migration", "biome"],
        },
    },
    "Ecosystem": {
        "keywords": ["food chain", "food web", "trophic level", "ecological pyramid",
                     "primary productivity", "gpp", "npp", "decomposition", "nutrient cycling",
                     "ecological succession", "hydrarch", "xerarch", "climax community",
                     "standing crop", "detritus", "energy flow", "ten percent law", "carbon cycle",
                     "phosphorus cycle"],
        "concepts": {
            "Productivity & Energy Flow": ["primary productivity", "gpp", "npp", "energy flow",
                                           "ten percent law", "standing crop"],
            "Food Chains & Ecological Pyramids": ["food chain", "food web", "trophic level",
                                                  "ecological pyramid", "detritus"],
            "Decomposition & Nutrient Cycling": ["decomposition", "nutrient cycling", "carbon cycle",
                                                 "phosphorus cycle"],
            "Ecological Succession": ["ecological succession", "hydrarch", "xerarch", "climax community"],
        },
    },
    "Biodiversity and Conservation": {
        "keywords": ["biodiversity", "species richness", "hotspot", "endemic", "extinction",
                     "red data book", "in situ", "ex situ", "biosphere reserve", "national park",
                     "sanctuary", "sacred grove", "rivet popper", "alexander von humboldt",
                     "species area relationship", "iucn", "endangered"],
        "concepts": {
            "Biodiversity Patterns": ["biodiversity", "species richness", "species area relationship",
                                      "alexander von humboldt", "latitudinal gradient"],
            "Loss of Biodiversity": ["extinction", "endangered", "rivet popper", "alien species",
                                     "habitat loss", "red data book"],
            "Conservation Strategies": ["in situ", "ex situ", "biosphere reserve", "national park",
                                        "sanctuary", "sacred grove", "hotspot", "iucn"],
        },
    },
    "Environmental Issues": {
        "keywords": ["air pollution", "water pollution", "eutrophication", "algal bloom",
                     "greenhouse effect", "global warming", "ozone depletion", "cfc",
                     "acid rain", "electrostatic precipitator", "catalytic converter",
                     "biomagnification", "montreal protocol", "joint forest management",
                     "chipko", "solid waste", "noise pollution"],
        "concepts": {
            "Air Pollution & Control": ["air pollution", "electrostatic precipitator",
                                        "catalytic converter", "noise pollution", "acid rain"],
            "Water Pollution & Eutrophication": ["water pollution", "eutrophication",
                                                 "algal bloom", "biomagnification", "bod"],
            "Global Warming & Ozone Depletion": ["greenhouse effect", "global warming",
                                                 "ozone depletion", "cfc", "montreal protocol"],
            "Waste Management & Conservation Movements": ["solid waste", "joint forest management",
                                                          "chipko", "deforestation"],
        },
    },
}
