"""Rich course catalogue detail for the Acharya/LMS course pages.
Ported from the retired learn.trigunai.com page (2026-06-30). One entry per LMS course id.
The add-trigunai-course skill appends a new entry here when a course is added."""

COURSE_DETAILS = {
    "agentic": {
        "tagline": "Build real, working AI agents that do useful work - tool use, memory, planning, multi-step autonomy - on today's APIs.",
        "level": "Beginner -> Practitioner",
        "modules": 9,
        "duration": "3 months",
        "what_you_build": [
            "A deployed agent doing a real job on a schedule",
            "A single tool-calling agent that grows into a multi-agent workflow",
            "A packaged business Ops Agent handed to a non-technical user",
        ],
        "curriculum": [
            "What an agent actually is - LLM + a loop + tools + memory; goal in, actions out, when it stops",
            "Your first tool-calling agent - function/tool calling, the agent loop, parsing tool requests, termination",
            "Tools & integrations - connect web search, files, a database, a Google Sheet, email",
            "Memory & context - short-term vs long-term, retrieval (RAG basics), managing the context window",
            "Planning & multi-step reasoning - task decomposition, ReAct, reflection and self-correction",
            "Reliability & guardrails - structured/JSON output, validation, retries, human-in-the-loop, cost control",
            "Multi-agent systems - orchestrator + worker agents, handoffs, when multiple agents genuinely help",
            "Deploy your agent - run it on a server/schedule, a minimal UI, logging and monitoring",
            "Ship a real business agent - package the Ops Agent, hand it to a non-technical user, measure time saved",
        ],
        "prerequisites": "A laptop + an API key (Claude / OpenAI). Light Python helps, but the agent writes most of the code.",
        "outcome": "A deployed agent doing a real job on a schedule - and the patterns to build the next one.",
    },
    "remote-swe": {
        "tagline": "AI didn't kill the software job - it killed the engineer who can't direct AI. Master DSA, system design, and the AI-collaboration interview round, and land a remote offer.",
        "level": "Intermediate -> Hired",
        "modules": 12,
        "duration": "3 months",
        "what_you_build": [
            "The judgment to command an AI coding agent - read its code, catch its mistakes, ship faster and safer",
            "A live job pipeline run in parallel from week one (resume, outreach, applications, mocks)",
            "An agent-assisted capstone project for your portfolio",
        ],
        "curriculum": [
            "Complexity & the operator's eye - Big-O, arrays, hashing, two-pointers, sliding window; reading AI code. Job: resume + LinkedIn rebuilt for remote",
            "Linear structures, search & trees - stacks/queues, binary search, linked lists, trees, tries. Job: remote-company list + referral outreach",
            "Recursion, backtracking & graphs - subsets/permutations, BFS/DFS, topological sort, DP intro. Job: first applications go out",
            "DP, greedy, heaps + first mock - knapsack/LIS/interval DP, greedy, heaps, intervals. Milestone: first timed DSA mock. Job: GitHub/portfolio polish",
            "Low-Level Design (LLD) - OOP, SOLID, top 5 design patterns, API design. Job: STAR story bank, first screens",
            "High-Level Design I - caching, databases, load balancing, CAP, back-of-envelope estimation. Job: phone-screen practice",
            "High-Level Design II - message queues (Kafka vs RabbitMQ), sharding, rate limiting, idempotency, observability. Job: take-home playbook",
            "System-design case studies - design Twitter, YouTube, Uber, Splitwise, Google Drive. Milestone: mock interviews with real engineers",
            "The AI-command round (signature) - critique an agent's design, spot hallucinated APIs, find the bugs while they watch",
            "AI pair-programming under pressure - spec -> generate -> review -> test loop; refactor, debug, security review. Job: final rounds",
            "Targeted revision + your-stack depth - doubt-sheet sweep, CS fundamentals, resume projects deep. Job: negotiation + evaluating offers",
            "Final mocks, capstone & close - full-loop mocks + agent-assisted capstone. Capstone: portfolio build + close the remote offer",
        ],
        "prerequisites": "A laptop + an AI coding agent (Claude / ChatGPT / Cursor). Assumes you've seen DSA once (a from-zero ramp is available). ~10 hrs/week for 3 months.",
        "outcome": "You leave hireable, not just certified - able to direct an AI agent and crack the AI-era remote interview.",
    },
    "ml-and-math": {
        "tagline": "Understand and build the core of modern ML - the math you actually need, then neural nets, embeddings, diffusion, and training. Intuition first, code second.",
        "level": "Beginner -> Builder",
        "modules": 10,
        "duration": "3 months",
        "what_you_build": [
            "A small model built and trained end-to-end on a real GPU",
            "A neural net and training loop coded from scratch, then rebuilt in PyTorch",
            "A capstone ML project - classifier, embedding search, or generator",
        ],
        "curriculum": [
            "The map - what ML is, the faculties-of-mind frame, supervised / unsupervised / RL in one picture",
            "The math you actually need - vectors, matrices, dot products, gradients, visual and intuitive",
            "Intuition = function approximation - a neuron, a layer, a network, the forward pass, by hand",
            "Getting better = gradient descent - loss, backpropagation, the training loop coded from scratch",
            "From scratch -> PyTorch - the same network in a real framework on a real GPU; tensors, autograd",
            "Meaning = embeddings & vector space - word and image embeddings, similarity, vector search",
            "Imagination = generative models - autoencoders -> intuition behind diffusion -> a tiny generator",
            "Attention & transformers - why attention won, and a minimal transformer block built piece by piece",
            "Training in practice - data, overfitting, regularization, evaluation, the real GPU training workflow",
            "A real ML project, end-to-end - pick a classifier, embedding search, or generator; train, evaluate, show",
        ],
        "prerequisites": "A laptop; GPU access provided for the training modules. Comfortable with basic Python; high-school math, refreshed in-course.",
        "outcome": "You can read, build, and train a small model end-to-end - and you finally get what's under the hood.",
    },
    "physical-ai": {
        "tagline": "The embodiment half. Train reinforcement-learning policies in NVIDIA Isaac Sim, on provided GPU, and watch them learn inside a VR headset.",
        "level": "Intermediate",
        "modules": 8,
        "duration": "3 months",
        "what_you_build": [
            "A control policy you trained yourself in simulation",
            "A PPO-trained robot that learns to reach its goal",
            "Your trained policy exported, rendered, and viewed running in VR",
        ],
        "curriculum": [
            "Simulation & digital twins - why we train robots in sim first; what a physics simulator does",
            "Isaac Sim / Isaac Lab setup (provided) - get into the NVIDIA stack on provided GPU",
            "RL basics for control - agents, environments, rewards, episodes, aimed at movement not games",
            "Designing the reward - the craft that makes or breaks a policy; shaping behavior through reward",
            "Training your first policy - run PPO, read the curves, get a robot that learns to reach its goal",
            "Sim-to-real concepts - domain randomization, the reality gap, moving a policy toward the real world",
            "Teleoperation & VR embodiment - drive and watch the policy from a Quest headset",
            "Deploy & view your trained policy - export the policy, render it, watch your trained robot run in VR",
        ],
        "prerequisites": "The premium tier - provided NVIDIA GPU + Isaac Sim + live cohort. Some Python and ML basics help.",
        "outcome": "A control policy you trained yourself in simulation, plus the sim-to-real and teleoperation concepts behind real robots.",
    },
    "vr-mr-app": {
        "tagline": "Use AI coding agents (Claude Code) + Unity to build a real VR/MR app from scratch - hand tracking, passthrough MR, multiplayer - and submit it to Meta's Store. No coding experience required.",
        "level": "Beginner -> Shipped",
        "modules": 11,
        "duration": "3 months",
        "what_you_build": [
            "A real VR/MR app running on your headset",
            "An app submitted to Meta's App Lab - something you can hand an interviewer",
            "Multiplayer, mixed-reality passthrough, and hand-tracking features",
        ],
        "curriculum": [
            "Setup - Unity, Quest & your dev environment; Unity 6 + Meta XR SDK, a room running on your headset",
            "Your AI coding partner - building VR with Claude Code; the 5-part VR prompt template",
            "Hands & controllers - hand tracking + controllers, grab/throw with physics, haptic feedback",
            "VR UI - world-space menus, buttons & panels; poke + laser interaction without making people sick",
            "Environment & audio - skyboxes, Quest-friendly lighting, particles, spatial audio",
            "Locomotion - teleport, smooth move, snap turn, comfort vignette, letting the user choose comfort",
            "Saving data & session logic - PlayerPrefs + JSON persistence, a Menu->Session->Summary state machine",
            "Multiplayer basics - Photon Fusion free tier, networked head+hands avatars, spatial voice chat",
            "Mixed reality & passthrough - Quest 3 passthrough, Scene API, spatial anchors",
            "Performance & polish - profiler, draw-call batching, ASTC textures, holding 72fps, the Meta VRC checklist",
            "Ship it - developer account, keystore signing, release APK, store listing, submit for review",
        ],
        "prerequisites": "A Windows PC + a Meta Quest 2/3/Pro + a USB-C cable. No prior Unity or VR experience.",
        "outcome": "A real VR/MR app running on your headset and submitted to Meta's App Lab - something you can hand an interviewer.",
    },
    "vr-game": {
        "tagline": "Design, build, and ship a complete VR game - mechanics, enemy AI, game feel, and a Meta Store launch. The deepest build we teach.",
        "level": "Intermediate -> Shipped",
        "modules": 12,
        "duration": "3 months",
        "what_you_build": [
            "A complete, playable VR game on your headset - enemies, progression, game feel",
            "A Meta Store submission - the portfolio piece that proves you can ship, not just prototype",
        ],
        "curriculum": [
            "Game design for VR - the core loop, player fantasy, comfort-first design, scoping a game you can finish",
            "Project architecture & your AI coding partner - scene/manager structure, game state machine, Claude Code",
            "Player & game locomotion that feels powerful - smooth move, teleport, dash, climb; comfort options",
            "Hands as gameplay - grab, wield, throw; two-handed weapons, physics interactions, holstering",
            "Your core mechanic & game systems - health, score, combos, inventory; iterate one mechanic to fun",
            "Enemy AI & combat - NavMesh agents, behavior state machines, wave spawning, melee + ranged, hit detection",
            "Game feel & juice - haptics, hit-stop, particle FX, screen effects; making hits land",
            "Spatial audio & adaptive music - 3D positional sound, dynamic music layers, audio cues",
            "Levels & environment - level design for VR, set dressing, lighting and occlusion, a full playable level",
            "In-game UI & menus that don't break immersion - diegetic HUD, main menu, pause, score screen",
            "Save, progression & balancing - persistence, unlocks, difficulty curves, playtesting to fun",
            "Optimize & ship to the Meta Store - hold 72 fps under combat load, build, store listing, submit",
        ],
        "prerequisites": "A Windows PC + a Meta Quest 2/3/Pro + a USB-C cable. The VR/MR App course (or equivalent Unity + Quest basics) helps but isn't required - setup is recapped in module 2.",
        "outcome": "A complete, playable VR game with enemies, progression, game feel, and a Meta Store submission.",
    },
    "screen-game": {
        "tagline": "Model your own assets in Blender, build the game in Unity, write the code with AI agents - and ship a complete flat-screen game for PC and mobile. No VR headset needed.",
        "level": "Beginner -> Shipped",
        "modules": 12,
        "duration": "3 months",
        "what_you_build": [
            "A complete, playable flat-screen game with your own Blender-modelled 3D assets",
            "A game published to itch.io and ready for Google Play",
            "The full pipeline: art AND code AND ship",
        ],
        "curriculum": [
            "Game design & scope for a flat-screen game - genre, core loop, top-down vs 3rd-person vs 2.5D",
            "Your toolchain - Blender + Unity + AI coding agents; how the three fit; project setup",
            "Blender fundamentals - model your first game asset; low-poly, game-ready topology",
            "UV unwrapping & texturing - UVs, materials, baking, PBR textures; look good AND run fast",
            "Rigging & animation in Blender - armatures, skinning, idle/walk/run/action",
            "The Blender -> Unity pipeline - exporting FBX/glTF, import settings, materials in URP, the round-trip",
            "Player controller & camera - character movement, the new Input System, Cinemachine cameras",
            "Core mechanic & game systems - the central mechanic plus health, score, inventory, iterated to fun",
            "Enemy AI & challenge - NavMesh agents, behavior state machines, encounters by genre",
            "Game feel, FX & audio - particles, juice, screen feedback, sound design and music",
            "Levels, UI & progression - level design, menus and HUD, save systems, difficulty tuning, playtesting",
            "Optimize & ship to PC + mobile - frame budget, draw calls, LODs, builds for PC and Android, publish to itch.io and Google Play",
        ],
        "prerequisites": "A Windows or Mac PC. No VR headset, no paid software - Blender and Unity are both free. Everything is installed in module 2.",
        "outcome": "A complete, playable flat-screen game - your own assets, your own gameplay - published and downloadable.",
    },
    "ai-video-factory": {
        "tagline": "Turn a script into a finished, narrated, captioned video - in your own GPU-powered studio. 15 days, multiple styles, copyright-clean, at scale.",
        "level": "Creator -> Studio owner",
        "modules": 15,
        "duration": "15 days",
        "what_you_build": [
            "A working AI video factory you own (the skill, not a subscription)",
            "Your first 3 published videos in any style - faceless explainers, motion-graphics, b-roll, shorts, bilingual",
            "A one-command, reproducible factory with presets per style",
        ],
        "curriculum": [
            "The AI Video Factory - the script-in/video-out model; the 5 layers (brain, voice, visuals, captions, compositor)",
            "Your cloud GPU + the brain - cheapest GPU options (RunPod / Vast.ai / AWS); LLM + image + voice behind one proxy; cost control",
            "Script -> narration - writing scripts for TTS; voice engines (edge-tts -> F5-TTS -> premium); per-scene audio",
            "Visuals I - AI images - photoreal & stylized stills; prompt craft for b-roll; building a shot list",
            "Visuals II - image -> motion - animating stills into living clips; subtle vs strong motion; multi-shot scenes",
            "Captions that pop - word-synced kinetic captions (auto-timed); lower-third labels; fonts & styling",
            "The compositor - layering background + overlays + captions + audio; clean export. Milestone: first complete faceless video",
            "Music & sound, copyright-clean - AI music beds; ducking under the voice; why copyright-clean matters",
            "Style 2 - motion-graphics / explainer - teaching diagrams, kinetic text, animated cards",
            "Style 3 - shaders + the talking-head reality - audio-reactive backgrounds; the honest truth about AI talking-heads",
            "Localization & reach - translate + re-voice into other languages with a one-swap workflow; bilingual channels",
            "Automation & the one-command factory - templates, presets per style, batching, reproducible runs",
            "Your factory, your way - tailor it to faceless YouTube, course/edu, product/marketing, social shorts; SEO basics",
            "Productize - clients & B2B - packaging as a service; pricing; intake -> delivery; the support trap to avoid",
            "Ship & scale - publishing workflow (YouTube API + scheduling); content calendar; 30-day plan. Capstone: publish your first 3 videos",
        ],
        "prerequisites": "A laptop + a modest cloud-GPU budget (~$1/hr) + a couple of API keys. No video-editing skill, no ML background - the AI writes most of the code; you direct.",
        "outcome": "A working AI video factory you own plus your first 3 published videos - any style, on demand, copyright-clean.",
    },
    "ai-music-factory": {
        "tagline": "Turn a prompt or your lyrics into finished, mastered, copyright-clean music - songs, beats, focus & meditation tracks - in your own GPU studio. And build your own AI singer.",
        "level": "Creator -> Label of one",
        "modules": 15,
        "duration": "15 days",
        "what_you_build": [
            "A working AI music factory you own",
            "Your own AI singer - a voice you own, consistent across every song",
            "Your first released tracks - songs, beats, focus/meditation, in 50+ languages, monetization-safe",
        ],
        "curriculum": [
            "The AI Music Factory - prompt/lyrics -> finished mastered track; the model landscape; copyright-clean = monetization-safe",
            "Your GPU + the engine - cheap cloud GPU; install the copyright-clean engine (ACE-Step class); cost control",
            "Prompting music: style & control - prompt craft for genre/mood/instruments/BPM; style presets; reference-style matching, legally",
            "Songs with vocals & lyrics - AI-written lyrics; lyric -> full vocal song; 50+ languages; song structure",
            "Any length: extend & structure - seamless crossfade extension; intros/outros; loop-ready beds; 2 min -> 1 hour",
            "Focus / study / sleep + brainwave tones - isochronic & binaural (beta/alpha/theta); 432Hz; honest claims",
            "Meditation, raga & wellness - 432Hz Indian-classical, sitar/sarangi healing, ambient drones. Milestone: a complete meditation track",
            "Beats, lofi & instrumentals - lofi chill, hip-hop beats, instrumental beds for creators; stems",
            "Build your AI singer I - record the voice; the recording protocol (consent, vowels & sargam, ~25-30 min)",
            "Build your AI singer II - train & sing; voice-conversion (RVC) training. Milestone: a song in your own AI singer's voice",
            "Precise melodies - singing synthesis (SVS / DiffSinger): render a melody you compose (MIDI) vs dice-roll generation",
            "Mastering & polish - loudness (LUFS for streaming), EQ, stereo width, fades; final MP3 / WAV",
            "Automate the factory - one-command presets per style; batching; templates; a repeatable pipeline",
            "Publish & monetize, copyright-clean - distribution (DistroKid / YouTube / Spotify); proving tracks are clean; sync / licensing",
            "Ship & scale - a release calendar; building a catalog; your AI singer as a brand. Capstone: release your first 3 tracks + your AI singer",
        ],
        "prerequisites": "A laptop + a modest cloud-GPU budget (~$1/hr) + a basic mic (only for the singer days). No music theory, no production background - the AI writes the lyrics and melodies; you direct.",
        "outcome": "A working AI music factory you own, your own AI singer, and your first released tracks - all safe to monetize.",
    },

    "ai-pm": {
        "tagline": "Scope, ship, and run AI products that actually work. The PM playbook for an AI world - feasibility, data strategy, generative AI, and the responsible-AI gate, applied to real products.",
        "level": "PM -> AI PM",
        "modules": 8,
        "duration": "8 weeks",
        "what_you_build": [
            "An AIPM one-pager that scopes a real AI product end to end (problem -> data -> approach -> metrics -> responsible-AI -> ops)",
            "A 'should this use ML / generative AI?' feasibility decision for one of your own features, with the non-ML baseline",
            "A data-readiness + responsible-AI ship-gate checklist applied to a live case",
        ],
        "curriculum": [
            "The AI PM mindset - the PM as translator between business value, user need, and what data makes possible; the 5 shifts an AI product forces",
            "AI landscape I - AI vs ML vs DL vs Data Science; supervised / unsupervised / reinforcement learning; the 'is this even an ML problem?' checklist",
            "AI landscape II + AI-first thinking - matching problem shape to model family; designing for the wrong answer, confidence in the UX, cold-start, the feedback loop",
            "AI/ML strategy I - prioritizing initiatives by value x feasibility, build vs buy vs API, the non-ML baseline, and data foundations (quality, splits, leakage, bias)",
            "AI/ML strategy II - the ML lifecycle / MLOps, model drift, latency-cost tradeoffs; the responsible-AI gate (fairness, privacy, explainability, human-in-the-loop)",
            "Generative AI for product - generative vs discriminative, LLMs, hallucination and context window; the prompt -> RAG -> fine-tune ladder; prompt engineering as a craft",
            "Reading a model - linear regression as the worked example: features, fitting, error, R-squared / MAE / RMSE, overfitting vs underfitting, trust the test set",
            "Capstone - the reusable AIPM one-pager applied end to end to a real AI product",
        ],
        "prerequisites": "No coding required. Some product or business context helps; every AI concept is taught from scratch.",
        "outcome": "Scope an AI feature, judge feasibility, design the data and evaluation strategy, run the responsible-AI gate, and talk credibly with ML and data teams.",
    },
}
